const { spawn } = require("child_process");

let exportPath = "";
let projectPath = "";
let projectName = "";

exports.audioExtensions = [".mp3", ".m4a", ".wav", ".flac"];
exports.imageExtensions = [".png", ".jpg", ".jpeg", ".webp"];


exports.setExportPath = path => {
	exportPath = path;
}

exports.getExportPath = () => {
	return exportPath;
}

exports.setProjectPath = path => {
	projectPath = path;
}

exports.getProjectPath = () => {
	return projectPath;
}

exports.setProjectFileName = name => {
	projectName = name;	
}

exports.getProjectFileName = () => {
	return projectName;
}

exports.cmdExec = function(cmd, args, dataCallback = () => {}, returnProcess = () => {}) {
	//Returns a promise
	return new Promise((resolve, reject) => {
		console.log(`\n\n\n${cmd} ${args.join(" ")}\n\n\n`);
		const s = spawn(cmd, args);

		returnProcess(s);

		//Prints any data generated by the command to the console
		s.stdout.on("data", (data) => {
			dataCallback(data.toString());
		});

		//Prints the error to the console
		s.stderr.on("data", (data) => {
			data = data.toString();
			dataCallback(data);
			console.log(data);
		});

		//Returns the exit code of the command
		s.on("close", (code) => {
			if(code != 0) {
				console.log("\n\nerror: " + code);
				reject(code);
			}
			resolve(code);
		});
	});
}

exports.exportPath = exportPath;
exports.projectPath = projectPath;